apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/HE41T/argocd-test.git'  # Git repo ของคุณ
    targetRevision: main
    path: '.'                                               # path ที่มี index.html
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Deployment สำหรับ serve index.html ด้วย nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: test-app-html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.9.0
          env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/HE41T/argocd-test.git"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_ROOT
              value: "/git"
            - name: GIT_SYNC_WAIT
              value: "30"
          volumeMounts:
            - name: html-volume
              mountPath: /git
      volumes:
        - name: html-volume
          emptyDir: {}

---
# Service แบบ NodePort
apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: default
spec:
  type: NodePort
  selector:
    app: test-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080   # กำหนด NodePort เอง
